name: 'Performance Comparison for M2 Extensions'
author: 'ExtDN'
description: 'compares performance before and after installing a Magento 2 extension'
inputs:
  github-token:
    description: 'The GitHub authentication token'
    required: true
    default: ${{ github.token }}
  baseline-file:
    required: true
    description: 'Path to blackfire.io json profile before'
    default: 'baseline.json'
  after-file:
    required: true
    description: 'Path to blackfire.io json profile after'
    default: 'after.json'
  threshold:
    required: false
    description: 'Performance threshold'
    default: '25'
runs:
  using: 'node12'
  main: 'dist/index.js'
